### ISSUE TITLE
make command fails on linux

### ISSUE THREAD

**Issue by miracleanupam** [tuomaura/cs-e4300_testbed#1]
`cd base`
`make`
command fails on linux.

![image](https://user-images.githubusercontent.com/13483731/99913622-50474f80-2d01-11eb-8f38-83c03cfc8124.png)

**Comment by miracleanupam** [comment]
Following modification on base.sh file seem to work. 


`sudo echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections`
`sudo echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections`

`sudo apt-get install -y net-tools locate vim nano tcpdump dnsutils traceroute curl git-core bzip2 npm nodejs conntrack`

**Comment by EErikas** [comment]
You can also set the line endings from CRLF to LF with a text editor of your choice (I used VS Code), that fixes the issue as well

**Comment by EErikas** [comment]
Also, this issue and solutions apply to macOS as well
